on:
  push:
    branches:
      - master

   
    


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to Docker hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAM }}  --password ${{ secrets.DOCKER_TOCC }}
         
      - name: "Bulding docker image"
        run: docker build -t ${{ secrets.DOCKER_USERNAM }}/myimage . 

      - name: "pushing to Docker hub" 
        run: docker push ${{ secrets.DOCKER_USERNAM }}/myimage

